### ISSUE TITLE
Document running Spark jobs on a Kerberised cluster

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/spark-k8s-operator#356] opened 2024-02-13 10:12 UTC
As a Spark developer I would like to be able to run Spark jobs on a cluster where one or more services have Kerberos enabled. There are additional setup required to get a Spark job to run with Kerberos, including providing keytab, Kerberos configuration, service configuration and Spark context config.

We should document how to run an example Spark job that connects to a kerberos-enabled HDFS and Hive service.

**Comment by adwk67** [comment] 2024-02-13 10:15
A spark-job that uses the secret operator to generate keytabs for named users can be found here: https://github.com/stackabletech/hdfs-topology-provider/pull/5/files#diff-49100e41e40194b8d1f7aba8218bec678d9a9817efd5346b4609a92269721264

**Comment by sbernauer** [comment] 2024-05-02 11:51
Duplicate of https://github.com/stackabletech/issues/issues/530, closing this as well. This is included in the end-to-end-security demo

**Closed by sbernauer** 2024-05-02 11:51 UTC
