### ISSUE TITLE
Tests don't run on managed k8s

### ISSUE THREAD

**Issue by fhennig** [stackabletech/spark-k8s-operator#58] opened 2022-05-02 12:27 UTC
Nikolaus reported to us that the tests don't run on managed k8s. Here are the links to the logs:

IONOS: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Spark%20K8s%20Operator%20Integration%20Tests%20(flex)/15/
Azure: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Spark%20K8s%20Operator%20Integration%20Tests%20(flex)/16/
AWS: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Spark%20K8s%20Operator%20Integration%20Tests%20(flex)/17/

Needs investigation

This is done when the integration tests run on managed K8s.

**Comment by lfrancke** [comment] 2022-07-13 08:50
The tests do run and are "green" everywhere. On IONOS it does not work as intended but it does work.
Closing because there's nothing we can do here.

**Closed by lfrancke** 2022-07-13 08:50 UTC
